CREATE TABLE availability
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parking_spot_id BIGINT,
    status          VARCHAR(255)                            NOT NULL,
    timestamp       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_availability PRIMARY KEY (id)
);

CREATE TABLE parking_spot
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code    VARCHAR(255)                            NOT NULL,
    type    VARCHAR(255)                            NOT NULL,
    active  BOOLEAN                                 NOT NULL,
    zone_id BIGINT,
    CONSTRAINT pk_parking_spot PRIMARY KEY (id)
);

CREATE TABLE sensor
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference       VARCHAR(255)                            NOT NULL,
    type            VARCHAR(255),
    active          BOOLEAN                                 NOT NULL,
    parking_spot_id BIGINT,
    CONSTRAINT pk_sensor PRIMARY KEY (id)
);

CREATE TABLE zone
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    hourly_rate DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_zone PRIMARY KEY (id)
);

ALTER TABLE parking_spot
    ADD CONSTRAINT uc_parking_spot_code UNIQUE (code);

ALTER TABLE sensor
    ADD CONSTRAINT uc_sensor_reference UNIQUE (reference);

ALTER TABLE zone
    ADD CONSTRAINT uc_zone_name UNIQUE (name);

ALTER TABLE availability
    ADD CONSTRAINT FK_AVAILABILITY_ON_PARKING_SPOT FOREIGN KEY (parking_spot_id) REFERENCES parking_spot (id);

ALTER TABLE parking_spot
    ADD CONSTRAINT FK_PARKING_SPOT_ON_ZONE FOREIGN KEY (zone_id) REFERENCES zone (id);

ALTER TABLE sensor
    ADD CONSTRAINT FK_SENSOR_ON_PARKING_SPOT FOREIGN KEY (parking_spot_id) REFERENCES parking_spot (id);